### ISSUE TITLE
Documentation/FAQ: background and compare/contrast

### ISSUE THREAD

**Issue by neiljaywarner** [olexale/bdd_widget_test#18]
The https://pub.dev/packages/flutter_gherkin author got a bit of a head start on this and so I'm comparing and contrasting for my company. 

Can you please share some thoughts on pros/cons from your perspective - eg were you aware of his project, and whether yes/no, what are you trying to do that he isn't doing?

I'm also checking into it myself.  Too bad i can't use both if desired.  it seems nice that yours is a dev dependency only, and your youtube video is great, and if he doesnt' support widget tests in the "test" folder that's pretty big...

**Comment by olexale** [comment]
Before bdd_widget_tests development, I investigated alternatives including fluter_gherkin, ogurets, and others. 

My motivation for creating yet another BDD framework came from two aspects: 
1. **Widget tests**. Of course, there is a huge value in integration tests but I use BDD not only for its primary goal - communication within the team regarding the functionality - but for the development as well. On my current project, we have ~500 widget tests that pass for less than two minutes and ~120 integration tests that pass for 4-5 hours. That makes it impossible to use integration tests in the test-first approach when you run all tests with pretty much every change to the code base.  
2. **Simplicity** is the key. When the framework forces you to become a Regex jedi, use additional tools, or if you can mess things because you misconfigured something - this is not the best user experience. I use code generation a lot on my projects, so I decided to delegate all the boilerplate to a robot and use existing Flutter mechanisms to generate and run tests. When things go wrong it is trivial to debug tests that were written in a way a regular developer would write them.

**Comment by neiljaywarner** [comment]
this is pretty good. thanks
