### ISSUE TITLE
Cannot share steps between feature files with different hierarchy level

### ISSUE THREAD

**Issue by GuillaumeMorinQc** [olexale/bdd_widget_test#42]
In our project we would like to organize our feature files like this: 

- Category 1
    - Sub-Category 1
        - Feature 1.1
    - Sub-Category 2
        - Feature 1.2
    - Feature 1 
- Category 2
    - Feature 2
    - Feature 3

Since feature files does not share the same level hierarchically, multiple step folders are created even with  a relative stepFolderName.
Result : 
- Category 1
    - step folder
    - Sub-Category 1
        - step folder
        - Feature 1.1
    - Sub-Category 2
        - step folder
        - Feature 1.2
    - Feature 1 
- Category 2
    - step folder
    - Feature 2
    - Feature 3

Can we have an option, so we can use a path relative to the project folder to generate steps independently of the feature files hierarchy ?

**Comment by DerJojo11** [comment]
Funny, was going to write a similar ticket today.
 
 We are having the same issue. We want to share one steps folder, thus we need an option to set a relative path, where all steps are defined. 
 
 With the current "hack" from the example it is not possible to map the above folder structure.
 
 Something like this:
 ```yaml
bdd_widget_test|featureBuilder:
        options:
            stepFolderPath: tests/steps
```

**Comment by GuillaumeMorinQc** [comment]
Either that, an option to specify that this path is relative to the root of the project or an expression like "{cwd}" at the beginning to resolve the current directory

**Comment by olexale** [comment]
That would be a breaking change, but we probably may introduce the syntax @DerJojo11 mentioned. I will have a look at this on the weekend.
Thanks for raising this issue!

**Comment by olexale** [comment]
This should work in `1.6.0`. If the step folder name starts with `./` or `../` - `bdd_widget_test` will treat it as relative to the feature folder path (the behavior prior to `1.6.0`). If not - it will look for a folder under the `test` folder.

So, if you want to have a single steps folder for the package, you may set it up like this:
```yaml
stepFolderPath: steps
```

Would you please test the new feature?

**Comment by DerJojo11** [comment]
Awesome! Thanks!

So I tried it out and it works good!

My Folder Structure looks like this:

- Feature1
    - Widgets
        - MyWidget
        - test_folder
            - another_widget_to_test 
- Feature2
    - Widgets
        - MyWidget
    

With this structure, I wish to have a folder structure like this:

- Test 
    - Feature1
        - Widgets
            - MyWidget test
            - test_folder
                - another_widget_to_test 
    - Feature2
        - .... 
     - steps
         - ...  

Right now, I can set the folderPath for it to:

```yaml
stepFolderPath: steps
```
and remove the stepFolderName. Then, this solution won't work.  We are creating then multiple step folder in each feature. 

But if I use only the

```yaml
stepFolderName: steps
```

Then we won't build new step folders. Instead only one Folder under the test fold has been created!  This is great! And we can ow use our own folder structure!

### Testing the  stepFolderPath

Then, I tried testing to change the folder path to something like this:


```yaml
stepFolderName: all_steps 
stepFolderPath: steps/all_steps
```

This won't work. Because we know create one all_steps folder under the test folder. 


## Conclusion 

Currently the way via stepFolderPath does not work. Or I did not understand it correctly. But my wish to create a step folder for all tests works fine! So thank you very much for that!

**Comment by olexale** [comment]
Sorry for the confusion, there is no `stepFolderPath` parameter, I copy-pasted it from your comment and didn't notice that it is not `stepFolderName`. My bad 🤦‍♂️

So, you may use the `stepFolderName` parameter to set both the name and the path and inside the new folder you may use whatever structure you like - put everything in the root of the folder or create sub-folders to match the structure of your test folder.

**Comment by olexale** [comment]
Do you think we may close the issue?

**Comment by DerJojo11** [comment]
Ah ok! 

For my part, we can close this issue. 😃
