### ISSUE TITLE
Config common steps folder instead of all steps [Question]

### ISSUE THREAD

**Issue by venkata-reddy-dev** [olexale/bdd_widget_test#70]
I want to configure predefined steps folder path  as line no 13 instead of line no 14 to 16

![Screenshot 2024-03-23 at 2 28 56 PM](https://github.com/olexale/bdd_widget_test/assets/32235964/356c0907-5d73-4662-895e-5a5bc49cc2a2)

**Comment by venkata-reddy-dev** [comment]
I feel,  it's really not developer friendly to update build.yml file  for each re-usable step configuration.

**Comment by olexale** [comment]
Hello! Thanks for raising the ticket.

This mechanism was not intended to be used for local steps with relative paths. If you follow the README, for external steps, you need to specify the package name. That was made for users to be intentional when they share (provide external step) or import (use existing step) anything from another package via `bdd_options` config.

It might be annoying to add common steps at the beginning of the project, but soon the list becomes stable as the majority of the steps will be feature-specific. If that's not true for your project and you expect the majority of steps to be shared between features, consider specifying the `stepFolderName` instead.

How many common steps that are private for the package do you expect to have in your project?

**Comment by venkata-reddy-dev** [comment]
@olexale 

My usecase : 

 I am writing the bdd test cases per screen, not per feature

Lets say I have 30 screens. I am creating 30 .feature files and 30 folders for each

For each screen I have below steps

Wip.....

**Comment by venkata-reddy-dev** [comment]
As per this doc, it is configuration for step folder name right,  not for re-usable steps config.

![Screenshot 2024-03-23 at 10 01 18 PM](https://github.com/olexale/bdd_widget_test/assets/32235964/da372c34-4265-40b5-b2d0-19384950fa9c)

**Comment by olexale** [comment]
`stepFolderName` will not only change the name, it may also make all feature files inside the package use a single directory, so you will get the steps reusability you requested. Inside this folder, you may create subfolders to prevent it from becoming a mess.

If that solution is not acceptable, my question is the same: how many common steps that are private for the package do you expect to have in your project?
So far it looks like you have two common steps (which I believe should be combined into a single one). That sounds not that bad if you had to write a single line in the config.

**Comment by venkata-reddy-dev** [comment]
@olexale  i get it now,  Thanks. 

For my project mostly 5 to 6 common steps. not more than this.
