### ISSUE TITLE
Bug: When using Patrol, the integration_test import is automatically added

### ISSUE THREAD

**Issue by DevFreeze** [olexale/bdd_widget_test#72]
When using Patrol, the test files have to be stored within the integration_test folder. This leads to the automatic import of the integration test dependency, which is not necessary.

`import 'package:integration_test/integration_test.dart';`

**Comment by olexale** [comment]
Hello, thanks for raising the issue!

That's not a bug, it's a feature. 😅 I don't think `bdd_widget_test` should know about Patrol, convenient_test, or any other testing package that has a custom testing function. Otherwise we'll end up with tons of "if-else"s that make no direct relationship to the package.
As soon as this behavior does not cause problems except for the annoying linter warning, my recommendation is [to tell the analyzer](https://dart.dev/tools/analysis#excluding-files) not to review generated files.

**Comment by DevFreeze** [comment]
It is not just a linter warning. It shows me an error. I don't have the dependency of integration_test in my pubspec.yaml, because I don't need it. I have to remove the import line by hand, every time I run the build runner.

I don't need the feature of automatically importing the patrol package. I just don't want to have packages imported, that I am not using :D

**Comment by olexale** [comment]
Ah, I see. Patrol 2 used integration tests as a dependency, but something changed in Patrol 3. In that case, that indeed might be more than just an annoying warning. I'll take a closer look at the problem during the weekend.

**Comment by olexale** [comment]
The issue should be fixed in `1.7.3`. Feel free to re-open the issue if there is an issue with the new version.
